### ISSUE TITLE
Extension not working with ERR_UNKNOWN_URL_SCHEME error

### ISSUE THREAD

**Issue by shashwat001** [shoshins/prevent-tab-closing#1]
Its not working. I am getting following error on devtool window
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://jilanldohabpfcpgihdcadeffoopefbb/core.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://jilanldohabpfcpgihdcadeffoopefbb/page.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by shoshins** [comment]
@shashwat001 thanks for the reporting. 

This is not an error, these warnings are optional and don't affect the plugin work. It works as planned.

By the way, warnings fix are going to be checked in v.0.0.2. I've sent it to the Chrome Store (In review right now).

As a temp solution to hide warnings, you can use this hotfix:
https://github.com/dequelabs/axe-core/issues/1977#issuecomment-695842704
